name : g6
services:
  postgres:
    image: postgres:16-alpine
    container_name: ${PROJECT_NAME}-db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - ${PROJECT_NAME}-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - ${PROJECT_NAME}-net

volumes:
  g6-data:
    external: true
networks:
 g6-net:
    external: true