name : g6-projectpreflight
services:
  postgres:
    image: postgres:16-alpine
    container_name: g6-db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - g6-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - g6-net

volumes:
  g6-data:
    external: true
networks:
  g6-net:
    external: true