name: g6
services:
  backend:
    container_name: ${PROJECT_NAME}-backend
    build: .
    ports:
      - ${PORT}:3000
    networks:
      - ${PROJECT_NAME}-net
    image: ${BACKEND_IMAGE_NAME}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
networks:
  g6-net: # Check by using `docker network ls` command
    external: true