name: g6
services:
  frontend:
    container_name: ${PROJECT_NAME}-frontend
    build: .
    ports:
      - ${NGINX_PORT}:5173
    networks:
      - ${PROJECT_NAME}-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
networks:
  g6-net: # Check by using `docker network ls` command
    external: true
